version: "3.2"
services:
  db:
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: users
      MYSQL_USER: App42PaaS
      MYSQL_PASSWORD: app9456

  adminer:
       image: adminer
       restart: always
       ports:
         - 8087:8080

  build:
    build: .
    volumes:
      - type: volume
        source: war
        target: /appMysql/target

  web:
    build: WebContent
    volumes:
      - type: volume
        source: war
        target: /usr/local/tomcat/webapps/
    ports:
      - 8084:8080
    depends_on:
      - db
      - adminer
      - build

volumes:
  war: